Enable multiple notebooks in notebook service; update notebook docs
Unidata/tds pull request #116
Opened 2020-10-01 23:16 UTC by haileyajohnson

- Update notebook service to have 2 endpoint: get a list all notebooks for a given dataset, and get a specific notebook
- Update dataset HTML page to show all available notebooks
- Change JupyterNotebook access type to new "DataViewer" access and remove from Access tab (only in Viewers tab)
- Change JupyterNotebookViewer logic:
     - Each notebook has its own JupyterNotebookViewer
     - New JupyterNotebookViewerService registers a list of all JupyterNotebookViewers
- added a, optional description and a type to Viewer objects
TODO:
- include screenshots in docs
- add tests for notebook service

2020-10-01 23:22 UTC, haileyajohnson commented
The new documentation for the Notebook service should probably be split up across the new sections, i.e. "Enable/Disable the service" is for TDS admins, while "Accessing Notebook" is for users/developers. I'm worried the changes in this PR will conflict with the changes @oxelson is working on.

2020-10-01 23:27 UTC, oxelson commented
@haileyajohnson - no worries. I’m keeping track of any changes to the docs to make sure they are added to my content.  Thanks for the heads up!

2020-10-02 20:01 UTC, lesserwhirls requested changes
> Reviewed 10 of 12 files at r1, 2 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/unidata/tds/116)* status: all files reviewed, 1 unresolved discussion (waiting on @haileyajohnson)

___
*[tds/src/main/java/thredds/server/notebook/JupyterNotebookViewerService.java, line 3 at r2](https://reviewable.io/reviews/unidata/tds/116#-MIepfw46ranAjGmep6K:-MIepfw46ranAjGmep6L:b9cqgw8) ([raw file](https://github.com/unidata/tds/blob/2e46390697f7ce33bbc2435b1c38876989403f0c/tds/src/main/java/thredds/server/notebook/JupyterNotebookViewerService.java#L3)):*
> ```
> import gov.noaa.pmel.sgt.MethodNotImplementedError;
> ```

I think maybe we should make our own `MethodNotImplementedException` for the TDS (it could live in the `tds` subproject under `thredds.server.exception`). Then we could add a handler for it under `thredds.server.TdsErrorHandling` to retrun a `501` (`HttpStatus.NOT_IMPLEMENTED`). There are other places in the code that could throw this error if it existed, but currently those just put out a log message. How do you feel about adding the exception and handler to this PR (no need to tackle the other cases here though)?


<!-- Sent from Reviewable.io -->

2020-10-02 20:03 UTC, lesserwhirls commented
Very nice! I really like the doc changes as well as the service changes. Only one comment for you to consider (it's could be something for a separate PR, but I think it could go on this one too).

2020-10-02 20:48 UTC, haileyajohnson commented
@lesserwhirls MethodNotImplementedException is implemented =)

2020-10-02 20:51 UTC, lesserwhirls approved these changes
Awesome! Everything looks good from my end. Thank you @haileyajohnson!

> Reviewed 3 of 3 files at r3.
> *[Reviewable](https://reviewable.io/reviews/unidata/tds/116#-:-MIf4IL3EK7bTT7dzFyi:b-fgp8xi)* status: :shipit: complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2020-10-02 20:52 UTC, merged