Readme
Unidata/tds pull request #119
Opened 2020-10-18 21:42 UTC by oxelson

Added simple (for now) README.txt files to these directories upon startup:

- ${tds.content.root.path}
- ${tds.content.root.path}/thredds/

We can flesh this out in more detail when we start to fine tune the docs.

Used provided code notation for file copies from startupContentDirectory to contentRootDir and threddsDirectory in TdsContext.java.  (E.g., no try with resources used.)

@lesserwhirls, please have a look and let me know what changes in text and/or file locations (startupContentDirectory) you'd like.  Thanks!

2020-10-21 16:23 UTC, lesserwhirls requested changes
Looks good! Just a few points, but nothing major. I thinking we'll eventually want to completely overwrite any existing README.txt that we find, but that will require some way of versioning them so that we only overwrite them when starting up a new version of the TDS for the first time.

> Reviewed 4 of 4 files at r1.
> *[Reviewable](https://reviewable.io/reviews/unidata/tds/119#-:-MKAxLLN9lvo82CecGhc:bq0ht5z)* status: all files reviewed, 3 unresolved discussions (waiting on @oxelson)

___
*[tds/src/main/webapp/WEB-INF/altContent/startup/thredds_README.txt, line 11 at r1](https://reviewable.io/reviews/unidata/tds/119#-MKAuDHN6GGY4pDbnMqa:-MKAuDHN6GGY4pDbnMqb:b-2hmtdg) ([raw file](https://github.com/unidata/tds/blob/58a10b70af31da9c133291e45119871d4f68cb5b/tds/src/main/webapp/WEB-INF/altContent/startup/thredds_README.txt#L11)):*
> ```vimhelp
> This directory will contain the following subdirectories and files:
> 
>   - cache/                Contains cashed TDS configuration information.
> ```

Maybe something like "Contains directories for temporary files and on-disk caches."
___
*[tds/src/main/webapp/WEB-INF/altContent/startup/thredds_README.txt, line 13 at r1](https://reviewable.io/reviews/unidata/tds/119#-MKAvH4SC3SM_fKw5j09:-MKAvH4TCzs_ZNCGJowf:b-939bdx) ([raw file](https://github.com/unidata/tds/blob/58a10b70af31da9c133291e45119871d4f68cb5b/tds/src/main/webapp/WEB-INF/altContent/startup/thredds_README.txt#L13)):*
> ```vimhelp
>   - cache/                Contains cashed TDS configuration information.
>   - catalog.xml           Main TDS client configuration file (a.k.a, the root catalog) used to serve data.
>   - enhancedCatalog.xml   Example client catalog file that comes with the TDS (referenced from catalog.xml).
> ```

This is also a configuration file (config catalog, not a client catalog). I think it's called "enhanced" because it shows examples of how to "enhance" the resulting client catalogs with additional metadata. It also shows examples of some more slightly advanced features for `datasetScan`, such as filtering and sorting.
___
*[tds/src/main/webapp/WEB-INF/altContent/startup/thredds_README.txt, line 15 at r1](https://reviewable.io/reviews/unidata/tds/119#-MKAwx12A9s6GCaHDJ1g:-MKAwx12A9s6GCaHDJ1h:b-t9j12p) ([raw file](https://github.com/unidata/tds/blob/58a10b70af31da9c133291e45119871d4f68cb5b/tds/src/main/webapp/WEB-INF/altContent/startup/thredds_README.txt#L15)):*
> ```vimhelp
>   - enhancedCatalog.xml   Example client catalog file that comes with the TDS (referenced from catalog.xml).
>   - logs/                 TDS-generated log files are located within this directory.
>   - notebooks/            Contains public endpoint .ipynb files for the TDS Jupyter Notebook service.
> ```

@haileyajohnson - sound good?


<!-- Sent from Reviewable.io -->

2020-10-21 17:09 UTC, haileyajohnson commented
___
*[tds/src/main/webapp/WEB-INF/altContent/startup/thredds_README.txt, line 15 at r1](https://reviewable.io/reviews/unidata/tds/119#-MKAwx12A9s6GCaHDJ1g:-MKB7bUY26QdNopatoo0:btahtzk) ([raw file](https://github.com/unidata/tds/blob/58a10b70af31da9c133291e45119871d4f68cb5b/tds/src/main/webapp/WEB-INF/altContent/startup/thredds_README.txt#L15)):*
<details><summary><i>Previously, lesserwhirls (Sean Arms) wrote…</i></summary><blockquote>

@haileyajohnson - sound good?
</blockquote></details>

sounds good to me!


<!-- Sent from Reviewable.io -->

2020-10-21 19:24 UTC, oxelson commented
OK @lesserwhirls.  Changes made.

> I thinking we'll eventually want to completely overwrite any existing README.txt that we find, but that will require some way of versioning them so that we only overwrite them when starting up a new version of the TDS for the first time.

Agreed!

2020-10-23 15:23 UTC, lesserwhirls approved these changes
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/unidata/tds/119)* status: all files reviewed, 2 unresolved discussions (waiting on @oxelson)



<!-- Sent from Reviewable.io -->

2020-10-23 15:24 UTC, lesserwhirls approved these changes
Awesome - thanks @oxelson! 

> *[Reviewable](https://reviewable.io/reviews/unidata/tds/119#-:-MKL2rCU-Ccl-q_ModjQ:bulyug3)* status: :shipit: complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2020-10-23 15:25 UTC, merged