Draft: Add some null checks in DatasetTrackerChronicle
Unidata/tds pull request #486
Opened 2024-03-28 21:27 UTC by WeatherGod

2024-03-28 21:27 UTC, WeatherGod commented
Currently trying this out in my k8s deployment since it is able to trigger failures to create a dataset tracker.

2024-03-28 21:44 UTC, WeatherGod commented
Ok, it reduces the amount of redundant stack traces in the logs, and it also helps the services to properly (or at least more correctly) error out rather than hang or otherwise barf.

2024-03-28 21:47 UTC, WeatherGod commented on tdcommon/src/main/java/thredds/server/catalog/tracker/DatasetTrackerChronicle.java
> +      catalogInitLog.error("Catalog chronicle map not properly initialized. Can't track dataset {}", dataset);
I'll note that this doesn't print out the name of the dataset, it prints out a repr of the dataset instance. I just followed the same pattern as above, if that's good enough.

2024-03-28 21:49 UTC, WeatherGod commented
I wouldn't know how to make tests for this since I don't know how to fail the creation of the chronicle file. Maybe point it to a directory that doesn't exist? Don't know if it makes directories automatically.

2024-03-28 21:53 UTC, WeatherGod commented
For the record from my logs:
```
# cat content/thredds/logs/catalogInit.log 
You are currently running TDS version 5.5-SNAPSHOT - 2024-03-28T04:58:45+0000
Latest Available TDS Version Info:
    latest development version = 5.5-SNAPSHOT
    latest release version = 5.4

=========================================================================================
ConfigCatalogInitialization readMode=always isStartup=true
DatasetTrackerChronicle failed on '/usr/local/tomcat/content/thredds/cache/catalog/chronicle.datasets.dat.1', delete catalog cache and reload 
java.io.IOException: Not enough space to fallocate 8 MiB to / unallocated was 0 MiB
	at net.openhft.chronicle.hash.impl.VanillaChronicleHash.fallocate(VanillaChronicleHash.java:1123) ~[chronicle-map-3.23.5.jar:3.23.5]
	at net.openhft.chronicle.hash.impl.VanillaChronicleHash.map(VanillaChronicleHash.java:1103) ~[chronicle-map-3.23.5.jar:3.23.5]
	at net.openhft.chronicle.hash.impl.VanillaChronicleHash.createMappedStoreAndSegments(VanillaChronicleHash.java:515) ~[chronicle-map-3.23.5.jar:3.23.5]
	at net.openhft.chronicle.map.ChronicleMapBuilder.createWithNewFile(ChronicleMapBuilder.java:1843) ~[chronicle-map-3.23.5.jar:3.23.5]
	at net.openhft.chronicle.map.ChronicleMapBuilder.createWithFile(ChronicleMapBuilder.java:1741) ~[chronicle-map-3.23.5.jar:3.23.5]
	at net.openhft.chronicle.map.ChronicleMapBuilder.createPersistedTo(ChronicleMapBuilder.java:1586) ~[chronicle-map-3.23.5.jar:3.23.5]
	at thredds.server.catalog.tracker.DatasetTrackerChronicle.open(DatasetTrackerChronicle.java:138) ~[classes/:5.5-SNAPSHOT]
	at thredds.server.catalog.tracker.DatasetTrackerChronicle.<init>(DatasetTrackerChronicle.java:79) [classes/:5.5-SNAPSHOT]
	at thredds.server.catalog.tracker.DatasetTrackerChronicle.<init>(DatasetTrackerChronicle.java:68) [classes/:5.5-SNAPSHOT]
	at thredds.core.ConfigCatalogInitialization.reread(ConfigCatalogInitialization.java:149) [classes/:5.5-SNAPSHOT]
	at thredds.core.ConfigCatalogInitialization.init(ConfigCatalogInitialization.java:131) [classes/:5.5-SNAPSHOT]
	at thredds.server.config.TdsInit.onApplicationEvent(TdsInit.java:149) [classes/:5.5-SNAPSHOT]
	at thredds.server.config.TdsInit.onApplicationEvent(TdsInit.java:67) [classes/:5.5-SNAPSHOT]
	at org.springframework.context.event.SimpleApplicationEventMulticaster.doInvokeListener(SimpleApplicationEventMulticaster.java:178) [spring-context-5.3.32.jar:5.3.32]
	at org.springframework.context.event.SimpleApplicationEventMulticaster.invokeListener(SimpleApplicationEventMulticaster.java:171) [spring-context-5.3.32.jar:5.3.32]
	at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:145) [spring-context-5.3.32.jar:5.3.32]
	at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:429) [spring-context-5.3.32.jar:5.3.32]
	at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:386) [spring-context-5.3.32.jar:5.3.32]
	at org.springframework.context.support.AbstractApplicationContext.finishRefresh(AbstractApplicationContext.java:949) [spring-context-5.3.32.jar:5.3.32]
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:594) [spring-context-5.3.32.jar:5.3.32]
	at org.springframework.web.context.ContextLoader.configureAndRefreshWebApplicationContext(ContextLoader.java:399) [spring-web-5.3.32.jar:5.3.32]
	at org.springframework.web.context.ContextLoader.initWebApplicationContext(ContextLoader.java:278) [spring-web-5.3.32.jar:5.3.32]
	at org.springframework.web.context.ContextLoaderListener.contextInitialized(ContextLoaderListener.java:103) [spring-web-5.3.32.jar:5.3.32]
	at org.apache.catalina.core.StandardContext.listenerStart(StandardContext.java:4441) [catalina.jar:8.5.100]
	at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:4899) [catalina.jar:8.5.100]
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:171) [catalina.jar:8.5.100]
	at org.apache.catalina.core.ContainerBase.addChildInternal(ContainerBase.java:710) [catalina.jar:8.5.100]
	at org.apache.catalina.core.ContainerBase.addChild(ContainerBase.java:687) [catalina.jar:8.5.100]
	at org.apache.catalina.core.StandardHost.addChild(StandardHost.java:660) [catalina.jar:8.5.100]
	at org.apache.catalina.startup.HostConfig.deployDirectory(HostConfig.java:1176) [catalina.jar:8.5.100]
	at org.apache.catalina.startup.HostConfig$DeployDirectory.run(HostConfig.java:1889) [catalina.jar:8.5.100]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515) [?:?]
	at java.util.concurrent.FutureTask.run(FutureTask.java:264) [?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) [?:?]
	at java.lang.Thread.run(Thread.java:829) [?:?]
DatasetTrackerChronicle failed on '/usr/local/tomcat/content/thredds/cache/catalog/chronicle.datasets.dat.1', delete catalog cache and reload 
java.io.IOException: Not enough space to fallocate 8 MiB to / unallocated was 0 MiB
	at net.openhft.chronicle.hash.impl.VanillaChronicleHash.fallocate(VanillaChronicleHash.java:1123) ~[chronicle-map-3.23.5.jar:3.23.5]
	at net.openhft.chronicle.hash.impl.VanillaChronicleHash.map(VanillaChronicleHash.java:1103) ~[chronicle-map-3.23.5.jar:3.23.5]
	at net.openhft.chronicle.hash.impl.VanillaChronicleHash.createMappedStoreAndSegments(VanillaChronicleHash.java:515) ~[chronicle-map-3.23.5.jar:3.23.5]
	at net.openhft.chronicle.map.ChronicleMapBuilder.createWithNewFile(ChronicleMapBuilder.java:1843) ~[chronicle-map-3.23.5.jar:3.23.5]
	at net.openhft.chronicle.map.ChronicleMapBuilder.createWithFile(ChronicleMapBuilder.java:1741) ~[chronicle-map-3.23.5.jar:3.23.5]
	at net.openhft.chronicle.map.ChronicleMapBuilder.createPersistedTo(ChronicleMapBuilder.java:1586) ~[chronicle-map-3.23.5.jar:3.23.5]
	at thredds.server.catalog.tracker.DatasetTrackerChronicle.open(DatasetTrackerChronicle.java:138) ~[classes/:5.5-SNAPSHOT]
	at thredds.server.catalog.tracker.DatasetTrackerChronicle.reinit(DatasetTrackerChronicle.java:120) [classes/:5.5-SNAPSHOT]
	at thredds.server.catalog.tracker.DatasetTrackerChronicle.<init>(DatasetTrackerChronicle.java:85) [classes/:5.5-SNAPSHOT]
	at thredds.server.catalog.tracker.DatasetTrackerChronicle.<init>(DatasetTrackerChronicle.java:68) [classes/:5.5-SNAPSHOT]
	at thredds.core.ConfigCatalogInitialization.reread(ConfigCatalogInitialization.java:149) [classes/:5.5-SNAPSHOT]
	at thredds.core.ConfigCatalogInitialization.init(ConfigCatalogInitialization.java:131) [classes/:5.5-SNAPSHOT]
	at thredds.server.config.TdsInit.onApplicationEvent(TdsInit.java:149) [classes/:5.5-SNAPSHOT]
	at thredds.server.config.TdsInit.onApplicationEvent(TdsInit.java:67) [classes/:5.5-SNAPSHOT]
	at org.springframework.context.event.SimpleApplicationEventMulticaster.doInvokeListener(SimpleApplicationEventMulticaster.java:178) [spring-context-5.3.32.jar:5.3.32]
	at org.springframework.context.event.SimpleApplicationEventMulticaster.invokeListener(SimpleApplicationEventMulticaster.java:171) [spring-context-5.3.32.jar:5.3.32]
	at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:145) [spring-context-5.3.32.jar:5.3.32]
	at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:429) [spring-context-5.3.32.jar:5.3.32]
	at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:386) [spring-context-5.3.32.jar:5.3.32]
	at org.springframework.context.support.AbstractApplicationContext.finishRefresh(AbstractApplicationContext.java:949) [spring-context-5.3.32.jar:5.3.32]
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:594) [spring-conte [...]

2024-03-28 21:56 UTC, WeatherGod commented
And, to be clear, this doesn't fix #484, it just makes thredds fail a bit more gracefully and produces slightly cleaner logs in this apparently rare situation.

2024-03-28 22:05 UTC, WeatherGod commented on tdcommon/src/main/java/thredds/server/catalog/tracker/DatasetTrackerChronicle.java
> +    }
This check might be superfluous. I'm not sure if ChronicleMapBuilder.of() can even return a null. At the moment for my situation, it throws an exception instead.

2024-04-11 16:52 UTC, tdrwenski requested changes

2024-04-12 18:24 UTC, tdrwenski approved these changes

2024-04-12 18:24 UTC, merged